- name: frontend setup
  hosts: all
  become: true
  tasks:
    - name: Disable Default Ngi
      ansible.builtin.shell: dnf module disable nginx -y

    - name: Enable Nginx 24
      ansible.builtin.shell: dnf module enable nginx:1.24 -y

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: Installed

    - name: Start Nginx Service
      ansible.builtin.systemd_service:
        name: nginx
        state: started