- name: Add the user
  ansible.builtin.user:
    name: useradd

- name: Recursively remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create an app directory content
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download app content and unzip the file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component_name}}-v3.zip
    dest: /app
    remote_src: yes

-