
- name: Add the user
  ansible.builtin.user:
    name: useradd

- name: Recursively remove directory
  ansible.builtin.file:
    path: https://roboshop-artifacts.s3.amazonaws.com
    state: absent

- name: Create an app directory content
  ansible.builtin.file:
    path: https://roboshop-artifacts.s3.amazonaws.com

- name: Download app content and unzip the file
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com
    dest: /app
    remote_src: yes

- name: Include task list in play
  ansible.builtin.include_tasks:
      file: nodejs.yml